//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string accountNo { get; set; }
        public string IdCard { get; set; }
        public string accountName { get; set; }
        public string accountPass { get; set; }
        public string accountType { get; set; }
    }
}
