//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public AccountInfo()
        {
            this.MoneyInfo = new HashSet<MoneyInfo>();
            this.LoanInfo = new HashSet<LoanInfo>();
            this.StudentLoan = new HashSet<StudentLoan>();
            this.BlackList = new HashSet<BlackList>();
        }
    
        public string accountNo { get; set; }
        public string IdCard { get; set; }
        public string accountName { get; set; }
        public string accountPass { get; set; }
        public string accountType { get; set; }
        public double accountBalance { get; set; }
    
        public virtual AccountFixed AccountFixed { get; set; }
        public virtual AccountFlex AccountFlex { get; set; }
        public virtual ICollection<MoneyInfo> MoneyInfo { get; set; }
        public virtual ICollection<LoanInfo> LoanInfo { get; set; }
        public virtual ICollection<StudentLoan> StudentLoan { get; set; }
        public virtual ICollection<BlackList> BlackList { get; set; }
    }
}
