//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> workDate { get; set; }
        public string telphone { get; set; }
        public string idCard { get; set; }
        public byte[] photo { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
