//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyInfo
    {
        public int Id { get; set; }
        public string accountNo { get; set; }
        public System.DateTime dealDate { get; set; }
        public string dealType { get; set; }
        public double dealMoney { get; set; }
        public double balance { get; set; }
    }
}
